#!/usr/bin/env bash

# REQUIREMENTS:
#   apt-get install aha
#
# Add to your crontab file:
#   LC_COLLATE="en_US.UTF-8"
#   CONTENT_TYPE="text/html; charset=utf-8"

function append_css() {
    CSS='
<style>
pre {
    font-size: 8pt;
    white-space: pre;
    line-height: 1;
}
span {
    display: inline-block;
    width: 1ch;
}
</style>
'
    awk -vcss="$CSS" '/<head/{print css} 1'
}

aha -s -b -x | append_css
