#!/usr/bin/env bash

SCRIPT_PATH=$(readlink -f $0)
SCRIPT_DIR=${SCRIPT_PATH%/*}
RUN_DIR=/var/run/lazysar
RUN_CMDS="$RUN_DIR/commands"
DEFAULTS_FILE="$HOME/.config/lazysar/defaults"
if [ ! -f "$DEFAULTS_FILE" ]; then
    DEFAULTS_FILE="$SCRIPT_DIR/defaults"
fi
PRESETS_FILE="$HOME/.config/lazysar/presets.json"
if [ ! -f "$PRESETS_FILE" ]; then
    PRESETS_FILE="$SCRIPT_DIR/presets.json"
fi

function check_zellij() {
    if ! command -v zellij >/dev/null; then
        echo "This command requires zellij to be installed!"
        exit 1
    fi
}

if [ "$1" = "panel" ]; then
    shift
    check_zellij

    cat $DEFAULTS_FILE > $RUN_CMDS

    LAYOUT=${1-basic}

    LAYOUT_PATH="$HOME/.config/zellij/layouts/${LAYOUT}.kdl"
    if [[ ! -f "$LAYOUT_PATH" ]]; then
        LAYOUT_PATH="$SCRIPT_DIR/layouts/${LAYOUT}.kdl"
    fi
    if [[ ! -f "$LAYOUT_PATH" ]]; then
        echo "Cannot find zellij layout $LAYOUT_PATH"
        exit 1
    fi

    SESSION=lazysar-$LAYOUT
    if zellij list-sessions 2>/dev/null | grep -q $SESSION; then
        zellij attach -f $SESSION
    else
        zellij -s $SESSION -l "$LAYOUT_PATH"
    fi
    exit
fi

if [ "$1" = "client" ]; then
    shift
    touch $RUN_CMDS

    while read COMMANDS; do
        if [ "$COMMANDS" == "STOP" ]; then
            break
        fi
        eval lazysar "$@" "--clear --title='' $COMMANDS"
    done < <(tail -n 1 -f $RUN_CMDS)
    exit
fi

if [ "$1" = "cmd" ]; then
    shift
    sleep 2
    trap "echo STOP > $RUN_CMDS" EXIT
    if command -v rlwrap >/dev/null; then
        (sleep 0.1 && zellij action write-chars -- "$(cat "$DEFAULTS_FILE")" ) &
        while true; do
            echo "Send args to panels (use history C-r, C-c to exit):"
            rlwrap -C lazysar $SCRIPT_PATH rlwrap || exit
        done
    else
        (sleep 1 && zellij action write-chars -- "echo \"$(cat "$DEFAULTS_FILE")\" > $RUN_CMDS" ) &
        $SHELL
    fi
    exit
fi

if [ "$1" = "rlwrap" ]; then
    shift
    echo -n "> "
    read COMMAND
    if [ -z "$COMMAND" ]; then
        COMMAND="$(cat "$DEFAULTS_FILE")"
        echo "Using defaults from $DEFAULTS_FILE: $COMMAND"
    fi
    if [[ "$COMMAND" =~ ^LOOP ]]; then
        SLEEP=5
        echo "Entering loop with ${SLEEP}s refresh ..."
        trap "echo 'Exiting ...'" INT
        while true; do
            echo "${COMMAND/LOOP /}" >> $RUN_CMDS
            sleep $SLEEP || break
        done
        COMMAND="STOP"
    fi
    echo "$COMMAND" >> $RUN_CMDS
    if [ "$COMMAND" = "STOP" ]; then
        exit 1
    fi
    exit
fi

"${SCRIPT_DIR}/.venv/bin/python" "${SCRIPT_DIR}/lazysar.py" --presets-file="${PRESETS_FILE}" "$@"
