#!/usr/bin/env bash

if ! command -v zellij >/dev/null; then
    echo "This command requires zellij to be installed!"
    exit 1
fi

SCRIPT_PATH=$(readlink -f $0)
SCRIPT_DIR=${SCRIPT_PATH%/*}

RUNDIR=/var/run/lazysar
cd $RUNDIR
touch $RUNDIR/commands

DEFAULT="$(cat $SCRIPT_DIR/defaults)"

if [ "$1" = "rlwrap" ]; then
    read COMMAND
    if [ -z "$COMMAND" ]; then
        echo "Using default: $DEFAULT"
        COMMAND="$DEFAULT"
    fi
    echo "$COMMAND" >> $RUNDIR/commands
    if [ "$COMMAND" = "STOP" ]; then
        exit 1
    fi
    exit
fi

trap "echo STOP >> $RUNDIR/commands" EXIT

while true; do
    echo ">> Send params to panels (use history, <ENTER> for default refresh, STOP to exit): "
    rlwrap -C lazysar $SCRIPT_PATH rlwrap || exit
done
